name: Output Issue Event Details

on:
  issues:
    types: [opened, edited, closed]

jobs:
  log-issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue details
        run: |
          echo "Action: ${{ github.event.action }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "User: ${{ github.event.issue.user.login }}"
          echo "URL: ${{ github.event.issue.html_url }}"